# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simple_calendar` gem.
# Please instead update this file by running `bin/tapioca gem simple_calendar`.

# source://simple_calendar//lib/simple_calendar.rb#1
module SimpleCalendar; end

# source://simple_calendar//lib/simple_calendar/calendar.rb#4
class SimpleCalendar::Calendar
  # @return [Calendar] a new instance of Calendar
  #
  # source://simple_calendar//lib/simple_calendar/calendar.rb#9
  def initialize(view_context, options = T.unsafe(nil), &block); end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#136
  def additional_days; end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#87
  def attribute; end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#79
  def date_range; end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#91
  def end_attribute; end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#132
  def end_date; end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#110
  def group_events_by_date(events); end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#32
  def locals(&block); end

  # Returns the value of attribute options.
  #
  # source://simple_calendar//lib/simple_calendar/calendar.rb#7
  def options; end

  # Sets the attribute options
  #
  # @param value the value to set the attribute options to.
  #
  # source://simple_calendar//lib/simple_calendar/calendar.rb#7
  def options=(_arg0); end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#83
  def partial_name; end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#24
  def render_in(view_context, &block); end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#99
  def sorted_events; end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#106
  def sorted_events_for(day); end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#124
  def start_date; end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#95
  def start_date_param; end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#42
  def td_classes_for(day); end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#59
  def tr_classes_for(week); end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#67
  def url_for_next_view; end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#71
  def url_for_previous_view; end

  # source://simple_calendar//lib/simple_calendar/calendar.rb#75
  def url_for_today_view; end

  # Returns the value of attribute view_context.
  #
  # source://simple_calendar//lib/simple_calendar/calendar.rb#7
  def view_context; end

  # Sets the attribute view_context
  #
  # @param value the value to set the attribute view_context to.
  #
  # source://simple_calendar//lib/simple_calendar/calendar.rb#7
  def view_context=(_arg0); end
end

# source://simple_calendar//lib/simple_calendar/calendar.rb#5
SimpleCalendar::Calendar::PARAM_KEY_BLACKLIST = T.let(T.unsafe(nil), Array)

module SimpleCalendar::CalendarHelper
  def calendar(options = T.unsafe(nil), &block); end
  def month_calendar(options = T.unsafe(nil), &block); end
  def week_calendar(options = T.unsafe(nil), &block); end
end

# source://simple_calendar//lib/simple_calendar/engine.rb#2
class SimpleCalendar::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.0.6/lib/active_support/callbacks.rb#68
    def __callbacks; end
  end
end

# source://simple_calendar//lib/simple_calendar/month_calendar.rb#2
class SimpleCalendar::MonthCalendar < ::SimpleCalendar::Calendar
  # source://simple_calendar//lib/simple_calendar/month_calendar.rb#3
  def date_range; end

  # source://simple_calendar//lib/simple_calendar/month_calendar.rb#7
  def url_for_previous_view; end
end

# source://simple_calendar//lib/simple_calendar/version.rb#2
SimpleCalendar::VERSION = T.let(T.unsafe(nil), String)

# source://simple_calendar//lib/simple_calendar/week_calendar.rb#2
class SimpleCalendar::WeekCalendar < ::SimpleCalendar::Calendar
  # source://simple_calendar//lib/simple_calendar/week_calendar.rb#16
  def date_range; end

  # source://simple_calendar//lib/simple_calendar/week_calendar.rb#12
  def end_week; end

  # source://simple_calendar//lib/simple_calendar/week_calendar.rb#8
  def number_of_weeks; end

  # source://simple_calendar//lib/simple_calendar/week_calendar.rb#23
  def url_for_previous_view; end

  # source://simple_calendar//lib/simple_calendar/week_calendar.rb#3
  def week_number; end
end
